version: '3.9'

volumes:
  postgres_chess:
    driver: local

services:
  postgres-chess:
    image: postgres:15.2
    container_name: postgres-chess
    volumes:
      - postgres_chess:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    environment:
      POSTGRES_DB: chess
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
